(()=>{
  const legacyDrawView=window.drawView;
  const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const display=(value,metric)=>value===null||value===undefined||value===''?(metric?.geographyLevel==='DISTRICT'?'District-level official data unavailable.':metric?.geographyLevel==='SUBDISTRICT'?'Subdistrict-level official data unavailable.':'Village-level official data unavailable.'):typeof value==='number'?value.toLocaleString('en-IN'):value;
  const statusClass=status=>String(status||'INSUFFICIENT_EVIDENCE').toLowerCase().replace(/_/g,'-');
  function evidence(metric,label){
    const status=metric?.status||'INSUFFICIENT_EVIDENCE',dataset=metric?.sourceDataset||'Official data unavailable';
    const meta='<p><b>Source:</b> '+esc(metric?.source||'—')+'<br><b>Publisher:</b> '+esc(metric?.sourcePublisher||'—')+'<br><b>Dataset:</b> '+esc(dataset)+'<br><b>Geography:</b> '+esc(metric?.geographyLevel||'—')+(metric?.geographyName?' · '+esc(metric.geographyName):'')+'<br><b>Data year / period:</b> '+esc(metric?.dataYear||'Not stated')+'<br><b>Freshness:</b> '+esc(metric?.freshness||'Not available')+(metric?.sourceUpdatedAt?'<br><b>Source updated:</b> '+esc(metric.sourceUpdatedAt):'')+(metric?.retrievedAt?'<br><b>Retrieved:</b> '+esc(metric.retrievedAt):'')+(metric?.detail?'<br><b>Note:</b> '+esc(metric.detail):'')+(metric?.sourceUrl?'<br><a target="_blank" href="'+esc(metric.sourceUrl)+'">Official source</a>':'')+'</p>';
    return '<article class="evidence-card"><div><p class="metric-label">'+esc(label)+'</p><strong>'+esc(display(metric?.value,metric))+'</strong></div><details class="evidence-details"><summary class="evidence-badge '+statusClass(status)+'">'+esc(status)+' · '+esc(dataset)+'</summary>'+meta+'</details></article>';
  }
  function marketRows(items){
    if(!items?.length)return '<p class="muted">No verified district market records are currently cached. Run the data.gov.in sync after configuring its API key.</p>';
    return '<div class="market-table"><div class="market-head"><span>Commodity</span><span>Modal price</span><span>Date</span><span>Market</span></div>'+items.map(item=>'<div><span>'+esc(item.value.commodity)+'</span><span>₹'+esc(item.value.modalPrice)+'/'+esc(item.value.unit==='INR/quintal'?'qtl':item.value.unit||'unit')+'</span><span>'+esc(item.value.arrivalDate||'Not stated')+'</span><span>'+esc(item.value.market)+'</span><details><summary>'+esc(item.status)+' · AGMARKNET</summary><p>District-level official market signal. '+esc(item.detail||'')+'</p></details></div>').join('')+'</div>';
  }
  function listEvidence(items,empty){return items?.length?'<ul class="evidence-list">'+items.map(item=>'<li><b>'+esc(item.value.crop||item.value.product||item.value.commodity||'Official record')+'</b> <small>'+esc(item.value.season||item.value.year||item.value.details||'')+'</small><details><summary class="evidence-badge '+statusClass(item.status)+'">'+esc(item.status)+' · '+esc(item.sourceDataset)+'</summary><p>'+esc(item.detail||'')+'</p></details></li>').join('')+'</ul>':'<p class="muted">'+esc(empty)+'</p>'}
  function genomeMarkup(genome){
    const g=genome||{},loc=g.location||{},metrics=g.metrics||{},eco=g.businessEcosystem||{},agri=g.agriculture||{},infrastructure=g.infrastructure||{};
    const location=loc.value||{};
    const insights=g.insights?.length?g.insights.map((item,index)=>'<article class="advisory '+(item.status==='DEMO_ADVISORY'?'demo-advisory':'')+'"><b>'+String(index+1)+'. '+esc(item.recommendation)+'</b><p>'+esc(item.reason)+'</p><p><span class="evidence-badge '+(item.status==='DEMO_ADVISORY'?'demo':'advisory')+'">'+esc(item.status==='DEMO_ADVISORY'?'DEMO ADVISORY':'AI ADVISORY')+' · '+esc(item.confidence)+' confidence</span></p><p class="muted">Evidence: '+item.evidence.map(e=>esc(e.sourceDataset)).join('; ')+'</p></article>').join(''):'<p class="muted">No evidence-supported business advisory is available yet. Add verified official-data caches, or gather local evidence before making a recommendation.</p>';
    const demoBanner=g.demoMode?'<section class="presentation-demo"><b>Presentation Demo Mode</b><p>'+esc(g.demoDisclosure)+'</p></section>':'';
    return '<section class="genome-heading"><p class="eyebrow">LOCAL BUSINESS & MARKET GENOME</p><h2>'+esc(location.village||'Verified location')+'</h2><p>'+esc(location.subdistrict||'')+' · '+esc(location.district||'')+' · '+esc(location.state||'Maharashtra')+(location.pincode?' · PIN '+esc(location.pincode):'')+'</p><details><summary class="evidence-badge verified">VERIFIED · LGD</summary><p>Government of India — Local Government Directory (LGD). Village code: '+esc(location.villageCode||'Not available')+'. Administrative identity only.</p></details></section>'+demoBanner+
      '<section class="genome-section"><div class="section-title"><div><p class="eyebrow">LOCAL PROFILE</p><h2>Historical Census context</h2></div><p class="muted">Census 2011 — never presented as current data.</p></div><div class="evidence-grid">'+evidence(metrics.population,'Population')+evidence(metrics.households,'Households')+evidence(metrics.workers,'Workers')+'</div></section>'+
      '<section class="genome-section"><div class="section-title"><div><p class="eyebrow">BUSINESS ECOSYSTEM</p><h2>Registered enterprise signals</h2></div><p class="muted">District-level UDYAM data, not all businesses.</p></div><div class="evidence-grid">'+evidence(eco.totalUdyamMsmes,'Registered UDYAM/MSMEs')+evidence(eco.services,'Services')+evidence(eco.manufacturing,'Manufacturing')+evidence(eco.msmesPerThousandPopulation,'MSMEs per 1,000 population')+'</div></section>'+
      '<section class="genome-section"><div class="section-title"><div><p class="eyebrow">AGRICULTURAL ECONOMY</p><h2>Official agriculture evidence</h2></div></div><div class="evidence-grid">'+evidence(agri.pmKisanBeneficiaries,'PM-KISAN registered beneficiaries')+'</div><h3>District crop-production records</h3>'+listEvidence(agri.majorCrops,'No verified district crop statistics are currently cached.')+'</section>'+
      '<section class="genome-section"><div class="section-title"><div><p class="eyebrow">MARKET SIGNALS</p><h2>Official mandi prices</h2></div><p class="muted">Relevant district market signal; village-to-market distance is not asserted.</p></div>'+marketRows(g.market?.commodities)+'</section>'+
      '<section class="genome-section"><p class="eyebrow">DISTRICT OPPORTUNITY</p><h2>One District One Product</h2>'+evidence(g.odop,'ODOP product')+'</section>'+
      '<section class="genome-section"><div class="section-title"><div><p class="eyebrow">VILLAGE INFRASTRUCTURE</p><h2>Census 2011 Village Amenities</h2></div><p class="muted">Historical amenities data only.</p></div><div class="evidence-grid">'+evidence(infrastructure.schools,'Schools')+evidence(infrastructure.banks,'Banks')+evidence(infrastructure.medicalFacilities,'Medical facilities')+evidence(infrastructure.roads,'Roads')+evidence(infrastructure.drinkingWater,'Drinking water')+evidence(infrastructure.electricity,'Electricity')+'</div></section>'+
      '<section class="genome-section"><p class="eyebrow">AI BUSINESS OPPORTUNITIES</p><h2>Evidence-backed advisory</h2>'+insights+'</section>'+
      '<section class="panel"><p class="eyebrow">LIVE NEARBY PLACES</p><h2>Optional Google Places enrichment</h2><p class="muted">Government data and live Google Places data remain separate. No fake competitors are shown when Google is unavailable.</p><label>Search radius <select id="radius"><option value="1000">1 km</option><option value="3000">3 km</option><option value="5000" selected>5 km</option></select></label><button class="primary" onclick="refreshNearby()">Check nearby businesses</button><p id="placeStatus"></p><div id="nearbyResult"></div><div class="layer-controls"><label><input type="checkbox" checked onchange="toggleLayer(\'competitors\',this.checked)"> Competitors</label><label><input type="checkbox" checked onchange="toggleLayer(\'banks\',this.checked)"> Banks</label><label><input type="checkbox" onchange="toggleLayer(\'markets\',this.checked)"> Markets</label><label><input type="checkbox" onchange="toggleLayer(\'suppliers\',this.checked)"> Suppliers</label></div><div id="realMap" class="real-map"></div></section>';
  }
  window.drawView=function(){
    if(activeView!=='market')return legacyDrawView();
    const view=document.getElementById('view');
    view.innerHTML=genomeMarkup(latest?.genome?.businessGenome);
  };
})();
