(()=>{
  const get=(object,path)=>path.split('.').reduce((value,key)=>value?.[key],object);
  const escape=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const indian=value=>'₹'+Math.round(Number(value)||0).toLocaleString('en-IN');
  const moneyWithLakh=value=>{const amount=Number(value)||0;if(amount<100000)return indian(amount);const lakh=Math.round(amount/100000*100)/100;return indian(amount)+' (≈ ₹'+lakh+' lakh)'};
  const endpoint=(url,payload)=>fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}).then(async response=>{const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed');return data});
  let language='en',en={},locale={},loanState=null,schemeRequest='';
  const t=(key,values={})=>{
    let value=get(locale,key)??get(en,key)??key;
    if(typeof value!=='string')return value;
    return value.replace(/\{(\w+)\}/g,(_,name)=>values[name]??'');
  };
  const localized=(scheme,key,fallback)=>get(locale,'schemeCopy.'+scheme.id+'.'+key)||get(en,'schemeCopy.'+scheme.id+'.'+key)||fallback;
  const profileDetails=()=>({gender:document.getElementById('gender')?.value||'',socialCategory:document.getElementById('socialCategory')?.value||'',stage:document.getElementById('stage')?.value||'new',streetVendor:document.getElementById('streetVendor')?.value||'no'});
  const decisionText=value=>({BORROW:{en:'BORROW',hi:'कर्ज ले सकते हैं',mr:'कर्ज घेऊ शकता'},'BORROW CAREFULLY':{en:'BORROW CAREFULLY',hi:'सावधानी से कर्ज लें',mr:'काळजीपूर्वक कर्ज घ्या'},'DO NOT BORROW YET':{en:'DO NOT BORROW YET',hi:'अभी कर्ज न लें',mr:'आता कर्ज घेऊ नका'}}[value]?.[language]||value);
  const statusText=value=>({COMFORTABLE:t('calculator.comfortable'),CAUTION:t('calculator.caution'),TOO_HIGH:t('calculator.tooHigh'),NEED_INCOME_INFO:t('calculator.needInfo')}[value]||value);

  function applyLanguage(){
    document.documentElement.lang=language;
    document.querySelectorAll('[data-i18n]').forEach(node=>{node.textContent=t(node.dataset.i18n)});
    document.querySelectorAll('[data-i18n-placeholder]').forEach(node=>{node.placeholder=t(node.dataset.i18nPlaceholder)});
    const select=document.getElementById('lang');if(select)select.value=language;
    if(typeof latest!=='undefined'&&latest)window.render();
  }
  const languageStorageKey='vyaparguide-language';
  window.setLanguage=async code=>{language=['en','hi','mr'].includes(code)?code:'en';sessionStorage.setItem(languageStorageKey,language);locale=language==='en'?en:await fetch('frontend/locales/'+language+'.json').then(response=>response.json());applyLanguage()};

  function profileForMatches(amount){return {...window.profile(),...profileDetails(),loanRequirement:Number(amount||latest?.financial?.recommendedLoan||0)};}
  async function loadSchemes(amount){
    if(typeof latest==='undefined'||!latest)return;
    const request=JSON.stringify(profileForMatches(amount));
    if(request===schemeRequest&&latest.schemeMatches)return;
    schemeRequest=request;
    try{latest.schemeMatches=await endpoint('/api/schemes/match',JSON.parse(request));if(activeView==='money')paintSchemeCards()}catch{latest.schemeMatches=[];paintSchemeCards()}
  }
  const list=items=>'<ul>'+items.map(item=>'<li>'+escape(item)+'</li>').join('')+'</ul>';
  function schemeCard(scheme){
    const copy={description:localized(scheme,'description',scheme.description),bestFor:localized(scheme,'bestFor',scheme.bestFor),benefits:localized(scheme,'benefits',scheme.benefits),need:localized(scheme,'need',scheme.documents),steps:localized(scheme,'steps',scheme.applicationSteps)};
    const isResource=scheme.status==='OFFICIAL_RESOURCE';
    return '<article class="scheme-card '+(isResource?'scheme-resource':'')+'"><div class="scheme-top"><div><span class="scheme-status">'+escape(isResource?t('finance.resource'):'GOVERNMENT SCHEME')+'</span><h3>'+escape(scheme.name)+'</h3><p>'+escape(copy.description)+'</p></div><div class="match-score"><b>'+scheme.eligibilityScore+'%</b><span>'+escape(isResource?t('finance.resource'):'Possible match')+'</span></div></div><p class="scheme-amount">'+escape(scheme.amountLabel||moneyWithLakh(scheme.maxAmount))+'</p><div class="scheme-columns"><div><h4>'+escape(t('finance.bestFor'))+'</h4><p>'+escape(copy.bestFor)+'</p><h4>'+escape(t('finance.benefits'))+'</h4>'+list(copy.benefits||[])+'</div><div><h4>'+escape(t('finance.need'))+'</h4>'+list(copy.need||[])+'</div></div><details><summary>'+escape(t('finance.why'))+'</summary>'+list(scheme.matchReasons||[]) +(scheme.warnings?.length?'<p class="scheme-warning">⚠ '+escape(t('finance.check'))+'</p>'+list(scheme.warnings):'')+'</details><details><summary>'+escape(t('finance.apply'))+'</summary>'+list(copy.steps||[])+'</details><p class="scheme-source"><b>'+escape(t('finance.source'))+':</b> '+escape(scheme.sourceName||scheme.source_name)+'<br><b>'+escape(t('finance.verified'))+':</b> '+escape(scheme.lastVerified||scheme.last_verified)+'<br><a target="_blank" rel="noreferrer" href="'+escape(scheme.officialSource||scheme.official_url)+'">'+escape(t('finance.apply'))+' ↗</a></p></article>';
  }
  function paintSchemeCards(){const holder=document.getElementById('schemeCards');if(holder)holder.innerHTML=(latest?.schemeMatches||[]).slice(0,4).map(schemeCard).join('')||'<p class="muted">'+escape(t('market.unavailable'))+'</p>'}
  function lenderCards(){return (latest?.funding||[]).slice(0,3).map(item=>'<article class="lender-card"><b>'+escape(item.provider)+'</b><h4>'+escape(item.product_name)+'</h4><p>'+escape(item.interest_rate)+'</p><a target="_blank" rel="noreferrer" href="'+escape(item.official_url)+'">'+escape(t('finance.source'))+' ↗</a></article>').join('');}
  function calculatorMarkup(){
    const financial=latest?.financial||{},business=latest?.b||{};
    const amount=loanState?.amount??financial.recommendedLoan??100000,sales=loanState?.monthlySales??business.revenue??'',expenses=loanState?.monthlyExpenses??Math.round((business.revenue||0)*(business.variable||0)+(business.fixed||0));
    return '<section class="loan-calculator panel"><p class="eyebrow">💰 '+escape(t('calculator.eyebrow'))+'</p><h2>'+escape(t('calculator.title'))+'</h2><p class="muted">'+escape(t('calculator.intro'))+'</p><div class="calculator-inputs"><label>'+escape(t('calculator.amount'))+'<input id="calcAmount" inputmode="numeric" type="number" min="1" value="'+escape(amount)+'"></label><label>'+escape(t('calculator.rate'))+'<input id="calcRate" inputmode="decimal" type="number" min="0" step="0.01" value="'+escape(loanState?.annualRate??12)+'"></label><label>'+escape(t('calculator.years'))+'<input id="calcYears" inputmode="numeric" type="number" min="1" max="40" value="'+escape(loanState?.years??3)+'"></label><label>'+escape(t('calculator.sales'))+'<input id="calcSales" inputmode="numeric" type="number" min="0" value="'+escape(sales)+'"></label><label>'+escape(t('calculator.expenses'))+'<input id="calcExpenses" inputmode="numeric" type="number" min="0" value="'+escape(expenses)+'"></label><label>'+escape(t('calculator.existing'))+'<input id="calcExisting" inputmode="numeric" type="number" min="0" value="'+escape(loanState?.existingMonthlyLoans??0)+'"></label></div><button type="button" class="primary calculator-button" onclick="calculateLoan()">'+escape(t('calculator.calculate'))+'</button><div id="calculatorResult" class="calculator-result" aria-live="polite"></div></section>';
  }
  function calculatorResult(){
    const holder=document.getElementById('calculatorResult');if(!holder)return;
    if(!loanState){holder.innerHTML='<p class="muted">'+escape(t('calculator.needInfo'))+'</p>';return}
    const status=loanState.affordability,explanation=status==='COMFORTABLE'?t('calculator.comfortableText'):status==='CAUTION'?t('calculator.cautionText'):status==='TOO_HIGH'?t('calculator.tooHighText'):t('calculator.needInfo');
    holder.innerHTML='<div class="calculator-estimate"><p class="eyebrow">'+escape(t('calculator.estimate'))+'</p><div class="calc-numbers"><div><span>'+escape(t('calculator.emi'))+'</span><b>'+indian(loanState.monthlyEmi)+'</b></div><div><span>'+escape(t('calculator.interest'))+'</span><b>'+indian(loanState.totalInterest)+'</b></div><div><span>'+escape(t('calculator.repayment'))+'</span><b>'+indian(loanState.totalRepayment)+'</b></div></div></div><div class="affordability '+String(status||'').toLowerCase()+'"><p class="eyebrow">'+escape(t('calculator.manage'))+'</p>'+(loanState.surplus!==null?'<p><b>'+escape(t('calculator.moneyLeft'))+':</b> '+indian(loanState.surplus)+'</p>':'')+'<h3>'+escape(statusText(status))+'</h3><p>'+escape(explanation)+'</p><small>'+escape(t('calculator.guideline'))+'</small></div><p class="finance-disclaimer">'+escape(t('calculator.estimateOnly'))+'</p>';
  }
  window.calculateLoan=async()=>{
    const input={amount:document.getElementById('calcAmount')?.value,annualRate:document.getElementById('calcRate')?.value,years:document.getElementById('calcYears')?.value,monthlySales:document.getElementById('calcSales')?.value,monthlyExpenses:document.getElementById('calcExpenses')?.value,existingMonthlyLoans:document.getElementById('calcExisting')?.value};
    try{loanState=await endpoint('/api/loan-calculator',input);calculatorResult();await loadSchemes(loanState.amount)}catch{const holder=document.getElementById('calculatorResult');if(holder)holder.innerHTML='<p class="form-error">'+escape(t('calculator.invalid'))+'</p>'}
  };
  function financeView(){return '<div class="finance-layout"><section class="scheme-area"><p class="eyebrow">'+escape(t('finance.eyebrow'))+'</p><h2>'+escape(t('finance.title'))+'</h2><p class="muted">'+escape(t('finance.intro'))+'</p><div id="schemeCards" class="scheme-cards"><p class="muted">'+escape(t('market.unavailable'))+'</p></div><section class="other-lenders"><p class="eyebrow">'+escape(t('finance.lender'))+'</p><p class="muted">'+escape(t('finance.lenderIntro'))+'</p><div class="lender-list">'+lenderCards()+'</div></section></section>'+calculatorMarkup()+'</div>'}
  function overviewView(){let x=latest;return '<div class="view-grid"><article class="panel"><p class="eyebrow">'+escape(t('overview.start'))+'</p><h2>'+escape(t('overview.path'))+'</h2>'+x.roadmap.slice(0,3).map((step,index)=>'<div class="step"><span>'+String(index+1)+'</span><div><b>'+escape(step.phase)+'</b><p>'+escape(step.target)+'</p></div></div>').join('')+'</article><article class="panel"><p class="eyebrow">'+escape(t('overview.watch'))+'</p><h2>'+escape(t('overview.mistakes'))+'</h2>'+x.risks.slice(0,3).map(risk=>'<div class="risk"><b>'+escape(risk.name)+'</b><p>'+escape(risk.action)+'</p></div>').join('')+'</article></div><section class="advisor panel"><div><p class="eyebrow">'+escape(t('overview.helper'))+'</p><h2>'+escape(t('overview.helperTitle'))+'</h2><p id="answer">'+escape(t('overview.helperHint'))+'</p></div><div><label class="sr-only" for="question">'+escape(t('overview.question'))+'</label><input id="question" placeholder="'+escape(t('overview.question'))+'"><button class="primary" type="button" onclick="ask()">'+escape(t('overview.ask'))+'</button></div></section>'}
  function areaMetric(label,metric){const value=metric?.value;let text=value===null||value===undefined?'—':typeof value==='object'?Object.values(value).filter(v=>typeof v==='string'||typeof v==='number').slice(0,2).join(' · '):value,source=metric?.dataYear?t('market.census',{year:metric.dataYear}):(metric?.status||'');return '<div class="area-metric"><span>'+escape(label)+'</span><b>'+escape(text)+'</b><small>'+escape(source)+'</small></div>'}
  function marketView(){const g=latest.genome?.businessGenome||{},location=g.location?.value||latest.profile,metrics=g.metrics||{},note=metrics.population?.source==='Census of India 2011'?t('market.censusNote'):t('market.noCensus');return '<section class="panel area-profile"><p class="eyebrow">'+escape(t('market.eyebrow'))+'</p><h2>'+escape(t('market.title'))+'</h2><div class="simple-list"><p><b>'+escape(t('market.village'))+':</b> '+escape(location.village||latest.profile.village)+'</p><p><b>'+escape(t('market.subdistrict'))+':</b> '+escape(location.subdistrict||latest.profile.subdistrict||'—')+'</p><p><b>'+escape(t('market.district'))+':</b> '+escape(location.district||latest.profile.district)+'</p><p><b>'+escape(t('market.identity'))+':</b> '+escape(location.villageCode||latest.profile.villageCode||'—')+'</p></div><p class="muted">'+escape(note)+'</p><div class="area-grid">'+areaMetric(t('market.population'),metrics.population)+areaMetric(t('market.households'),metrics.households)+areaMetric(t('market.workers'),metrics.workers)+areaMetric(t('market.literacy'),metrics.literacyRate)+'</div></section>'}
  function stressView(){return '<section class="panel"><p class="eyebrow">BUSINESS CHECK</p><h2>'+escape(t('nav.stress'))+'</h2><p>The business remains positive in <b>'+latest.sustainable+' of '+latest.stress.length+'</b> sample situations.</p><div class="scenario-grid">'+latest.stress.map(item=>'<div class="scenario '+escape(item.risk.toLowerCase())+'"><b>'+escape(item.name)+'</b><strong>'+indian(item.profit)+'</strong><small>'+escape(t('dashboard.left'))+'</small></div>').join('')+'</div></section>'}
  window.drawView=()=>{const view=document.getElementById('view');if(!view)return;if(activeView==='overview')view.innerHTML=overviewView();else if(activeView==='market')view.innerHTML=marketView();else if(activeView==='money'){view.innerHTML=financeView();loadSchemes(loanState?.amount);setTimeout(window.calculateLoan,0)}else view.innerHTML=stressView()};
  window.setView=view=>{activeView=view;window.render()};
  window.render=()=>{if(typeof latest==='undefined'||!latest)return;const x=latest,f=x.financial,d=document.getElementById('dash');document.getElementById('loading').hidden=true;d.hidden=false;d.className='dashboard';d.innerHTML='<div class="dash-head"><div><p class="eyebrow">'+escape(t('dashboard.blueprint'))+'</p><h2>'+escape(x.profile.business)+'</h2><p>'+escape(x.profile.village)+', '+escape(x.profile.district)+' · '+indian(x.profile.capital)+' '+escape(t('dashboard.available'))+'</p></div><button class="quiet" type="button" onclick="report()">'+escape(t('dashboard.print'))+'</button></div><div class="decision '+escape(x.borrow.decision.replaceAll(' ','-').toLowerCase())+'"><div><p class="eyebrow">'+escape(t('dashboard.decision'))+'</p><h1>'+escape(decisionText(x.borrow.decision))+'</h1><p>'+escape(x.borrow.why)+'</p><b>'+escape(t('dashboard.next'))+' '+escape(x.recommendation)+'</b></div><div class="decision-score"><strong>'+x.viability+'</strong><span>'+escape(t('dashboard.score'))+'</span></div></div><div class="key-metrics"><div class="metric"><span>'+escape(t('dashboard.local'))+'</span><strong>'+escape(x.localScore==null?'—':x.localScore+'/100')+'</strong><small>'+escape(t('dashboard.demoEstimate'))+'</small></div><div class="metric"><span>'+escape(t('dashboard.left'))+'</span><strong>'+indian(f.surplus)+'</strong><small>'+escape(t('dashboard.leftHelp'))+'</small></div><div class="metric"><span>'+escape(t('dashboard.safeLoan'))+'</span><strong>'+indian(f.recommendedLoan)+'</strong><small>'+escape(t('dashboard.reserve',{amount:indian(f.reserve)}))+'</small></div><div class="metric"><span>'+escape(t('dashboard.comfort'))+'</span><strong>'+escape(f.dscr)+'x</strong><small>'+escape(t('dashboard.comfortHelp'))+'</small></div></div><nav class="tabs">'+[['overview','overview'],['market','market'],['money','money'],['stress','stress']].map(([id,key])=>'<button type="button" class="'+(activeView===id?'selected':'')+'" onclick="setView(\''+id+'\')">'+escape(t('nav.'+key))+'</button>').join('')+'</nav><section id="view"></section><p class="notice">'+escape(x.notice)+'</p>';window.drawView()};
  const originalProfile=window.profile;window.profile=()=>({...originalProfile(),...profileDetails(),language:language});
  Promise.all([fetch('frontend/locales/en.json').then(r=>r.json()),fetch('frontend/locales/'+(sessionStorage.getItem(languageStorageKey)||'en')+'.json').then(r=>r.json())]).then(([english,chosen])=>{en=english;language=sessionStorage.getItem(languageStorageKey)||'en';locale=chosen;applyLanguage()}).catch(()=>{});
})();
