const MASK='places.id,places.displayName,places.formattedAddress,places.location,places.primaryType,places.types,places.googleMapsUri,places.businessStatus';
const cache=new Map(),ttl=600000;
const key=()=>process.env.GOOGLE_MAPS_API_KEY||process.env.GOOGLE_PLACES_SERVER_KEY;
const demo=(lat,lng,business)=>({mode:'DEMO',source:'Prototype local dataset',sourceUrl:null,retrievedAt:new Date().toISOString(),places:[{id:'demo-1',name:'Demo relevant business',category:business,layer:'competitors',lat:lat+.004,lng:lng+.003,address:'Demo location record'},{id:'demo-2',name:'Demo bank branch',category:'Bank',layer:'banks',lat:lat-.003,lng:lng+.004,address:'Demo location record'}]});
async function call(path,payload,mask=MASK){let r=await fetch('https://places.googleapis.com/v1/'+path,{method:'POST',headers:{'Content-Type':'application/json','X-Goog-Api-Key':key(),'X-Goog-FieldMask':mask},body:JSON.stringify(payload)});if(!r.ok)throw Error('Google Places request failed: '+r.status);return r.json()}
const normal=(p,layer='competitors')=>({id:p.id,name:p.displayName?.text||'Unnamed place',address:p.formattedAddress||'Address unavailable',lat:p.location?.latitude,lng:p.location?.longitude,category:p.primaryType||p.types?.[0]||'business',businessStatus:p.businessStatus||'Unknown',layer,mapsUrl:p.googleMapsUri||null});
const dist=(a,b,c,d)=>{let r=Math.PI/180,x=Math.sin((c-a)*r/2)**2+Math.cos(a*r)*Math.cos(c*r)*Math.sin((d-b)*r/2)**2;return Math.round(6371*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))*1000)};
export const mapConfig=()=>({mapsJsKey:process.env.GOOGLE_MAPS_MAPS_JS_KEY||'',enabled:Boolean(key()),provider:key()?'Google Places API (New)':'Demo fallback'});
export async function autocomplete(input){if(!key())return{mode:'DEMO',predictions:[]};let d=await call('places:autocomplete',{input,regionCode:'IN'},'suggestions.placePrediction.placeId,suggestions.placePrediction.text');return{mode:'LIVE',source:'Google Places API (New)',retrievedAt:new Date().toISOString(),predictions:(d.suggestions||[]).map(s=>({id:s.placePrediction?.placeId,text:s.placePrediction?.text?.text})).filter(x=>x.id)}}
export async function searchLocation(query){if(!key())return{mode:'DEMO',results:[]};let d=await call('places:searchText',{textQuery:query,regionCode:'IN',pageSize:5});return{mode:'LIVE',source:'Google Places API (New)',retrievedAt:new Date().toISOString(),results:(d.places||[]).map(normal)}}
export async function placeDetails(placeId){if(!key())return{mode:'DEMO',place:null};let r=await fetch('https://places.googleapis.com/v1/'+encodeURIComponent(placeId),{headers:{'X-Goog-Api-Key':key(),'X-Goog-FieldMask':'id,displayName,formattedAddress,addressComponents,location,googleMapsUri'}});if(!r.ok)throw Error('Google Place Details request failed: '+r.status);let p=await r.json(),components={};for(let c of p.addressComponents||[])for(let t of c.types||[])components[t]=c.longText||c.shortText;return{mode:'LIVE',source:'Google Places API (New)',place:{...normal(p),state:components.administrative_area_level_1||null,district:components.administrative_area_level_2||null,pin:components.postal_code||null,placeId:p.id}}}
export async function nearby({lat,lng,business,radius=5000}){let id=[lat,lng,business,radius].join('|'),old=cache.get(id);if(!key())return demo(lat,lng,business);try{let bias={circle:{center:{latitude:lat,longitude:lng},radius:Number(radius)}},queries=[{query:business,layer:'competitors'},{query:'banks',layer:'banks'},{query:'markets',layer:'markets'},{query:'suppliers',layer:'suppliers'}],responses=await Promise.all(queries.map(q=>call('places:searchText',{textQuery:q.query+' near '+lat+','+lng,regionCode:'IN',pageSize:20,locationBias:bias}).then(d=>({d,...q}))));let seen=new Set(),places=responses.flatMap(({d,layer})=>(d.places||[]).map(p=>normal(p,layer))).filter(p=>!seen.has(p.id)&&seen.add(p.id)).map(p=>({...p,distanceMeters:p.lat&&p.lng?dist(lat,lng,p.lat,p.lng):null})),out={mode:'LIVE',source:'Google Places API (New)',sourceUrl:'https://developers.google.com/maps/documentation/places/web-service',retrievedAt:new Date().toISOString(),places};cache.set(id,{at:Date.now(),out});return out}catch(e){if(old&&Date.now()-old.at<ttl)return{...old.out,mode:'CACHED',source:'Google Places API (New) short-lived cache',retrievedAt:new Date(old.at).toISOString(),warning:'Live request failed; showing demo fallback.'};return{...demo(lat,lng,business),warning:'Live Google request failed; showing demo fallback.'}}}
